service:
    name: cf-dynamic-image-example-new
  
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action: s3:PutObject
      Resource: arn:aws:s3:::${self:custom.userParams.CDN_BUCKET}/*
    - Effect: Allow
      Action: s3:GetObject
      Resource: arn:aws:s3:::${self:custom.userParams.PRIVATE_BUCKET}/*
  apiGateway:
    binaryMediaTypes:
      - "*/*"

custom:
  userParams:
    PRIVATE_BUCKET: shinemelb-private-bucket-cat
    CDN_BUCKET: shinemelb-cdn-bucket-cat

functions:
  cdn-image-new:
    runtime: nodejs12.x
    handler: src/index.handler
    memorySize: 3008
    events:
      - httpApi:
          path: /media/{width}/{image+}
          method: get
    environment:
      CDN_BUCKET_NAME: ${self:custom.userParams.CDN_BUCKET}
      PRIVATE_BUCKET_NAME: ${self:custom.userParams.PRIVATE_BUCKET}